services:
  - type: web
    name: dishabot-chatapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot_web.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
