services:
  - type: web
    name: dishabot-chatapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot_web.py
    envVars:
      - key: PORT
        value: 10000
